"""baseline schema

Revision ID: 088c8bf376d6
Revises:
Create Date: 2026-01-25 10:08:00.143195
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# NOTE:
# trade_mindset_tags intentionally excluded from baseline schema.
# Journal / mindset features will be added in later migrations once finalized.

# revision identifiers, used by Alembic.
revision = '088c8bf376d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'executions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('source_filename', sa.String(), nullable=True),
        sa.Column('ticker', sa.String(), nullable=False),
        sa.Column('side', sa.Enum('OPEN', 'CLOSE', name='exec_side'), nullable=False),
        sa.Column('direction', sa.Enum('LONG', 'SHORT', name='exec_direction'), nullable=False),
        sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column('remaining_qty', sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('fee', sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True),
                  server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'source',
            'source_filename',
            'ticker',
            'side',
            'direction',
            'price',
            'quantity',
            'timestamp',
            name='uq_execution_dedupe'
        )
    )

    op.create_table(
        'trade_entry_notes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('trade_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('entry_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('strategy', sa.String(), nullable=True),
        sa.Column('risk_pct', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('confidence_at_entry', sa.Integer(), nullable=True),
        sa.Column('optional_comment', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('trade_id')
    )
    op.create_index(
        op.f('ix_trade_entry_notes_user_id'),
        'trade_entry_notes',
        ['user_id'],
        unique=False
    )

    op.create_table(
        'trade_events',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('trade_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'event_type',
            postgresql.ENUM(
                'hold', 'partial', 'move_sl', 'scale_in', 'exit_early',
                name='trade_event_type_enum'
            ),
            nullable=False
        ),
        sa.Column(
            'reason',
            postgresql.ENUM(
                'plan_based', 'emotion_based', 'external_signal',
                name='trade_event_reason_enum'
            ),
            nullable=False
        ),
        sa.Column(
            'emotion',
            postgresql.ENUM(
                'calm', 'fear', 'greed', 'doubt', 'impatience',
                name='trade_emotion_enum'
            ),
            nullable=True
        ),
        sa.Column('emotion_note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_trade_events_user_id'),
        'trade_events',
        ['user_id'],
        unique=False
    )

    op.create_table(
        'trade_exit_notes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('trade_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'exit_type',
            postgresql.ENUM('tp', 'sl', 'manual', 'early', name='exit_type_enum'),
            nullable=False
        ),
        sa.Column('plan_followed', sa.Integer(), nullable=False),
        sa.Column(
            'violation_reason',
            postgresql.ENUM(
                'fomo', 'loss_aversion', 'doubt', 'impatience',
                name='violation_reason_enum'
            ),
            nullable=True
        ),
        sa.Column(
            'would_take_again',
            postgresql.ENUM(
                'yes', 'no', 'with_changes',
                name='would_take_again_enum'
            ),
            nullable=True
        ),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('trade_id')
    )
    op.create_index(
        op.f('ix_trade_exit_notes_user_id'),
        'trade_exit_notes',
        ['user_id'],
        unique=False
    )

    op.create_table(
        'execution_matches',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('close_execution_id', sa.Integer(), nullable=True),
        sa.Column('open_execution_id', sa.Integer(), nullable=True),
        sa.Column('matched_quantity', sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True),
                  server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['close_execution_id'], ['executions.id']),
        sa.ForeignKeyConstraint(['open_execution_id'], ['executions.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.add_column(
        'trades',
        sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False)
    )

    op.alter_column(
        'trades',
        'original_quantity',
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=False
    )

    op.alter_column(
        'trades',
        'entry_price',
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=False
    )

    op.alter_column(
        'trades',
        'risk_warnings',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True
    )

    op.alter_column(
        'trades',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()')
    )

    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_ticker'), 'trades', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_ticker'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')

    op.alter_column(
        'trades',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()')
    )

    op.alter_column(
        'trades',
        'risk_warnings',
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True
    )

    op.alter_column(
        'trades',
        'entry_price',
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=True
    )

    op.alter_column(
        'trades',
        'original_quantity',
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=True
    )

    op.drop_column('trades', 'quantity')
    op.drop_table('execution_matches')
    op.drop_index(op.f('ix_trade_exit_notes_user_id'), table_name='trade_exit_notes')
    op.drop_table('trade_exit_notes')
    op.drop_index(op.f('ix_trade_events_user_id'), table_name='trade_events')
    op.drop_table('trade_events')
    op.drop_index(op.f('ix_trade_entry_notes_user_id'), table_name='trade_entry_notes')
    op.drop_table('trade_entry_notes')
    op.drop_table('executions')
    # ### end Alembic commands ###

